# minio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.minio.name }} # minio
  namespace: {{ .Values.namespace.name }} # alfalfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.minio.name }} # minio
  template:
    metadata:
      labels:
        app: {{ .Values.minio.name }} # minio
    spec:
      containers:
        - name: {{ .Values.minio.container.name }} # minio
          image: {{ .Values.minio.container.image }} # minio/minio:RELEASE.2021-01-16T02-19-44Z
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name  }} #minio-secrets
                  key: AWS_ACCESS_KEY_ID #access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name  }}
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: {{ .Values.minio.container.ports.s3 }} # 9000