kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.minio.name  }}
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    {{ .Values.minio.persistence.accessModes }}
  resources:
    requests:
      storage:  {{ .Values.minio.persistence.size }}
