apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cosim.name }}
  namespace: {{  .Values.namespace.name  }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{  .Values.cosim.container.ports.port }}
      targetPort: {{  .Values.cosim.container.ports.targetPort }}
  selector:
    app: {{ .Values.cosim.name }}