apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.cosim.name }}
  namespace: {{  .Values.namespace.name  }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.cosim.name }}
    spec:
      initContainers:
        - name: init-wait-for-web
          image: alpine
          command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 {{ .Values.web.name }} {{ .Values.web.container.ports.http  }} && exit 0 || sleep 3; done; exit 1"]
        - name: init-change-permissions
          image: alpine
          command: ["/bin/sh", "-c", "chmod 777 /cosim/"]
          volumeMounts:
            - name: cosim-storage
              mountPath: /cosim/ip_op
      containers:
        - name: {{ .Values.cosim.name }} 
          image: {{ .Values.cosim.container.image}} 
          ports:
            - containerPort: {{  .Values.cosim.container.ports.port }} 
          volumeMounts:
            - name: {{ .Values.cosim.container.volumeMounts.name }} 
              mountPath: {{ .Values.cosim.container.volumeMounts.mountPath }}  
          resources:
            requests:
              memory: "10Gi"
            limits:
              memory: "15Gi"
          env:
            - name: TIME_STEP_SIZE
              value: "{{ .Values.cosim.env_params.TIME_STEP_SIZE }}"
            - name: TOTAL_EXPS
              value: "{{ .Values.cosim.env_params.TOTAL_EXPS }}"
            - name: DAYS_PER_EXP
              value: "{{ .Values.cosim.env_params.DAYS_PER_EXP }}"
            - name: STEPS_TO_RUN
              value: "{{ .Values.cosim.env_params.STEPS_TO_RUN }}"
            - name: NUM_MODELS
              value: "{{ .Values.cosim.env_params.NUM_MODELS }}"
            - name: NUM_PARALLEL_PROCESS
              value: "{{.Values.worker.replicas}}"

      volumes:
        - name: {{ .Values.cosim.container.volumeMounts.name }} 
          persistentVolumeClaim:
            claimName: {{ .Values.cosim.pvc.name}}
      restartPolicy: Never
