apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name  }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.mongo.label  }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Values.mongo.name  }}
      protocol: TCP
      port: {{ .Values.mongo.container.ports.db_port }}
