kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.certbot.name  }}
  namespace: {{  .Values.namespace.name  }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    {{ .Values.certbot.persistence.accessModes }}
  resources:
    requests:
      storage:  {{ .Values.certbot.persistence.size }}
