{{ if not .Values.nginx_https.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.certbot.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.certbot.name  }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.certbot.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.certbot.container.name }}
          image: {{ .Values.certbot.container.image }}
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            requests:
              cpu:  {{  .Values.certbot.container.resources.requests.cpu  }}
              memory:  {{  .Values.certbot.container.resources.requests.memory  }}
            limits:
              cpu:  {{  .Values.certbot.container.resources.limits.cpu  }}
              memory:  {{  .Values.certbot.container.resources.limits.memory  }}
          volumeMounts:
            - name: {{ .Values.certbot.name }}
              mountPath: /etc/letsencrypt/webroot
      volumes:
        - name: {{ .Values.certbot.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.certbot.name }}
{{ end }}
