apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.goaws.name  }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{  .Values.goaws.name  }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{  .Values.goaws.name  }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name:  {{  .Values.goaws.container.name  }}
          image:  {{  .Values.goaws.container.image  }}
          resources:
            requests:
              cpu:  {{  .Values.goaws.container.resources.requests.cpu  }}
              memory:  {{  .Values.goaws.container.resources.requests.memory  }}
            limits:
              cpu:  {{  .Values.goaws.container.resources.limits.cpu  }}
              memory:  {{  .Values.goaws.container.resources.limits.memory  }}
          ports:
             - containerPort: {{ .Values.goaws.container.ports.sns  }}
