apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.goaws.name   }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.goaws.name  }}
    release: {{ .Release.Name }}
  ports:
    - name: sns
      protocol: TCP
      port: {{ .Values.goaws.container.ports.sns   }}
