apiVersion: v1
kind: ConfigMap
metadata:
  name: {{  .Values.grafana.name  }}
  namespace: {{  .Values.namespace.name  }}
data:
{{ (tpl (.Files.Glob "configmaps/grafana/*").AsConfig . ) | indent 2  }}
