apiVersion: v1
kind: ConfigMap
metadata:
  name: {{  .Values.nginx_ingress.name  }}
  namespace: {{  .Values.namespace.name  }}
data:
{{ (tpl (.Files.Glob "configmaps/nginx-ingress/*").AsConfig . ) | indent 2  }}
