{{ if eq .Values.provider.name "rancher" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  rules:
  - host: {{ .Values.rancher.hostnames.web }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.web.name }}
          servicePort: {{ .Values.web.container.ports.http }}
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.rancher.hostnames.web }}
{{ end }}
