apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.load_balancer.name  }}
spec:
  type: LoadBalancer
  externalTrafficPolicy:  {{ .Values.load_balancer.externalTrafficPolicy }}
  selector:
    app: {{ .Values.load_balancer.label }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Values.load_balancer.ports.http_name }}
      protocol: {{ .Values.load_balancer.ports.http_protocol }} 
      port: {{ .Values.load_balancer.ports.http_port }}
    - name: {{ .Values.load_balancer.ports.https_name }}
      protocol:  {{ .Values.load_balancer.ports.https_protocol }}
      port:   {{ .Values.load_balancer.ports.https_port }}
    - name: {{ .Values.load_balancer.ports.sns_name }}
      protocol:  {{ .Values.load_balancer.ports.sns_protocol }}
      port:   {{ .Values.load_balancer.ports.sns_port }}
    - name: {{ .Values.load_balancer.ports.kibana_name }}
      protocol:  {{ .Values.load_balancer.ports.kibana_protocol }}
      port:   {{ .Values.load_balancer.ports.kibana_port }}
    - name: {{ .Values.load_balancer.ports.dashboard_name }}
      protocol:  {{ .Values.load_balancer.ports.dashboard_protocol }}
      port:   {{ .Values.load_balancer.ports.dashboard_port }}
  loadBalancerSourceRanges:
     - {{ .Values.load_balancer.loadBalancerSourceRanges }}
