{{ if .Values.env.public.HISTORIAN_ENABLE }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.influxdb.name  }}
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    {{ .Values.influxdb.persistence.accessModes }}
  resources:
    requests:
      storage:  {{ .Values.influxdb.persistence.size }}
{{ end }}