{{ if .Values.env.public.HISTORIAN_ENABLE }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.influxdb.name  }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.influxdb.label  }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Values.influxdb.name  }}
      protocol: TCP
      port: {{ .Values.influxdb.container.ports.db_port }}
{{ end }}