apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name  }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.redis.name  }}
    release: {{ .Release.Name }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.container.ports.redis }}
