apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }} #alfalfa
type: Opaque
data:
  {{- range $key, $val := .Values.env.private }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}